// <auto-generated />
using Api.PackDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace tetaix_circuit.Migrations
{
    [DbContext(typeof(PackContext))]
    partial class PackContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("tetaix_circuit.Modele.Circuit", b =>
                {
                    b.Property<int>("CircuitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("etat_circuit")
                        .HasColumnType("int");

                    b.Property<string>("nom_circuit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nombre_km")
                        .HasColumnType("int");

                    b.HasKey("CircuitId");

                    b.ToTable("Circuit");
                });

            modelBuilder.Entity("tetaix_circuit.Modele.Pack", b =>
                {
                    b.Property<int>("PackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CircuitId")
                        .HasColumnType("int");

                    b.Property<int>("VoitureId")
                        .HasColumnType("int");

                    b.Property<int>("nb_tour")
                        .HasColumnType("int");

                    b.Property<int>("nom_pack")
                        .HasColumnType("int");

                    b.HasKey("PackId");

                    b.HasIndex("CircuitId");

                    b.HasIndex("VoitureId");

                    b.ToTable("Pack");
                });

            modelBuilder.Entity("tetaix_circuit.Modele.Voiture", b =>
                {
                    b.Property<int>("VoitureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("etat_voiture")
                        .HasColumnType("int");

                    b.Property<string>("nom_voitiure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nombre_km")
                        .HasColumnType("int");

                    b.HasKey("VoitureId");

                    b.ToTable("Voiture");
                });

            modelBuilder.Entity("tetaix_circuit.Modele.Pack", b =>
                {
                    b.HasOne("tetaix_circuit.Modele.Circuit", "Circuit")
                        .WithMany()
                        .HasForeignKey("CircuitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tetaix_circuit.Modele.Voiture", "Voiture")
                        .WithMany()
                        .HasForeignKey("VoitureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Circuit");

                    b.Navigation("Voiture");
                });
#pragma warning restore 612, 618
        }
    }
}
